<Project>
  <PropertyGroup>
    <RevitVersion Condition="'$(RevitVersion)' == '' AND ('$(Configuration)' == '' OR '$(Configuration)' == 'Debug' OR '$(Configuration)' == 'Release')">2026</RevitVersion>
  </PropertyGroup>
  <Import Project="Sdk.props" Sdk="Nice3point.Revit.Sdk/6.2.3" />
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>RevitDevLoader</RootNamespace>
    <AssemblyName>RevitDevLoader.Addin.Modern</AssemblyName>
    <UseWPF>true</UseWPF>
    <ImplicitRevitUsings>false</ImplicitRevitUsings>
    <DeployAddin>false</DeployAddin>
    <LaunchRevit>false</LaunchRevit>
    <IsRepackable Condition="$([MSBuild]::IsOSPlatform('Windows'))">true</IsRepackable>
    <RepackBinariesExcludes>System*.dll</RepackBinariesExcludes>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Authors>Dinar Sharafutdinov</Authors>
    <Configurations>Debug;Release;Debug.R25;Debug.R26;Release.R25;Release.R26</Configurations>
  </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Nice3point.Revit.Api.RevitAPI" Version="$(RevitVersion).*"/>
        <PackageReference Include="Nice3point.Revit.Api.RevitAPIUI" Version="$(RevitVersion).*"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2"/>
        <PackageReference Include="Serilog" Version="4.0.0"/>
        <PackageReference Include="Serilog.Extensions.Logging" Version="8.0.0"/>
        <PackageReference Include="Serilog.Sinks.File" Version="6.0.0"/>
        <PackageReference Include="ILRepack" Version="2.0.46" PrivateAssets="all"/>
        <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" PrivateAssets="all"/>
    </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\RevitDevLoader.Core\RevitDevLoader.Core.csproj" />
    <Compile Include="..\RevitDevLoader.Addin.Shared\**\*.cs" Link="%(RecursiveDir)%(Filename)%(Extension)" />
    <Page Include="..\RevitDevLoader.Addin.Shared\Resources\*.xaml" Link="Resources\%(Filename)%(Extension)" />
  </ItemGroup>
  <Import Project="Sdk.targets" Sdk="Nice3point.Revit.Sdk/6.2.3" />
</Project>
